### ISSUE TITLE
agent ->buffer ->init 疑问

### ISSUE THREAD

**Issue by satng** [gonet2/agent#3]
![qq 20160927205721](https://cloud.githubusercontent.com/assets/6063500/18874711/4fc3a9b8-84f5-11e6-8710-8b9cae32bfe5.jpg)

在这里的for是不是没有释放？

**Comment by xtaci** [comment]
不需要释放啊

**Comment by satng** [comment]
睡一觉，再看就明白了。init只执行一次 ^_^
